language: java

dist: trusty

jdk:
  - openjdk11

install: mvn clean test -Ptravis -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    - JAVA_OPTS=-Xmx2g
